#!/usr/bin/env python3
"""Generate the "Test evidence" docs page from Surefire results.

Reads target/surefire-reports/TEST-*.xml (the authoritative record of
what actually ran) and enriches each test with its three-question
rationale block extracted from the test sources
(src/test/kotlin/**). Writes docs/tests/test-evidence.md, which the
Docs workflow feeds into MkDocs.

The page is GENERATED - it must never be checked in or edited by hand,
otherwise it becomes a drifting mirror of the suite (see the 2026-08-29
comment audit on mirrored facts). MkDocs' --strict build fails if this
script did not run first, which is the intended guard.

Usage: python3 .github/scripts/generate-test-catalog.py \
           [reports_dir] [test_src_dir] [output_md]
"""

import html
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

REPORTS_DIR = Path(sys.argv[1] if len(sys.argv) > 1 else "target/surefire-reports")
TEST_SRC_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else "src/test/kotlin")
OUTPUT = Path(sys.argv[3] if len(sys.argv) > 3 else "docs/tests/test-evidence.md")

FUN_RE = re.compile(r"^\s*fun `([^`]+)`\(")
QUESTIONS = [
    ("What is tested?", re.compile(r"What is to be tested\?")),
    ("How is success determined?", re.compile(r"How will the test case be deemed successful and why\?")),
    ("Why does it matter?", re.compile(r"Why is it important to test this test case\?")),
]


def extract_rationales(src_dir: Path) -> dict:
    """Map (top-level test class, test method name) -> {question: text}.

    The rationale block is the run of '//' comment lines directly after
    the test function's opening line; method names are sentence-shaped
    and unique per file, so the file's class name plus the method name
    is a sufficient key.
    """
    rationales = {}
    for kt in sorted(src_dir.rglob("*Test.kt")):
        clazz = kt.stem
        lines = kt.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            m = FUN_RE.match(line)
            if not m:
                continue
            # The rationale is the CONTIGUOUS comment run at the top of
            # the body; the blank line before the Given/When/Then
            # comments ends it.
            comment = []
            for follow in lines[i + 1:]:
                stripped = follow.strip()
                if stripped.startswith("//"):
                    comment.append(stripped[2:].strip())
                elif stripped == "" and not comment:
                    continue
                else:
                    break
            text = " ".join(comment)
            parsed = {}
            spans = [(q.search(text), label) for label, q in QUESTIONS]
            spans = [(mm.start(), mm.end(), label) for mm, label in spans if mm]
            spans.sort()
            for idx, (start, end, label) in enumerate(spans):
                stop = spans[idx + 1][0] if idx + 1 < len(spans) else len(text)
                answer = text[end:stop].strip()
                if answer:
                    parsed[label] = answer
            if parsed:
                rationales[(clazz, m.group(1))] = parsed
    return rationales


def load_suites(reports_dir: Path):
    """Group testcases: top-level class -> nested group -> [test names]."""
    suites = defaultdict(lambda: defaultdict(list))
    totals = {"tests": 0, "failures": 0, "errors": 0, "skipped": 0, "time": 0.0}
    times = defaultdict(float)
    for report in sorted(reports_dir.glob("TEST-*.xml")):
        root = ET.parse(report).getroot()
        totals["tests"] += int(root.get("tests", 0))
        totals["failures"] += int(root.get("failures", 0))
        totals["errors"] += int(root.get("errors", 0))
        totals["skipped"] += int(root.get("skipped", 0))
        totals["time"] += float(root.get("time", 0.0))
        for case in root.iter("testcase"):
            classname = case.get("classname", "")
            simple = classname.rsplit(".", 1)[-1]
            top, _, group = simple.partition("$")
            suites[top][group].append(case.get("name", ""))
            times[top] += float(case.get("time", 0.0))
    return suites, totals, times


def md_escape(text: str) -> str:
    return html.escape(text, quote=False)


def main() -> None:
    if not REPORTS_DIR.is_dir():
        sys.exit(f"error: {REPORTS_DIR} not found - run `mvn verify` first")
    rationales = extract_rationales(TEST_SRC_DIR)
    suites, totals, times = load_suites(REPORTS_DIR)

    out = []
    out.append("# Test evidence")
    out.append("")
    out.append(
        "> Generated by the Docs workflow from the Surefire results of the"
        " default (offline) test run and the rationale comments in the test"
        " sources. Do not edit by hand."
    )
    out.append("")
    out.append(
        f"The default run executed **{totals['tests']} tests**"
        f" ({totals['failures']} failures, {totals['errors']} errors,"
        f" {totals['skipped']} skipped) in {totals['time']:.1f}s, without a"
        " Kafka broker or Docker. Two further stages run deliberately"
        " outside this loop: the Testcontainers-based real-broker tests"
        " (`mvn -Pintegration test`) and the external-contract"
        " characterization tests (`mvn -Pexternal-contract test`) - see"
        " [CONTRIBUTING](https://github.com/Inqudium/tabellarium/blob/main/CONTRIBUTING.md)."
    )
    out.append("")
    out.append("| Component under test | Tests | Time |")
    out.append("|---|---:|---:|")
    for top in sorted(suites, key=lambda t: -sum(len(v) for v in suites[t].values())):
        count = sum(len(v) for v in suites[top].values())
        anchor = top.lower()
        out.append(f"| [`{top}`](#{anchor}) | {count} | {times[top]:.1f}s |")
    out.append("")

    for top in sorted(suites):
        count = sum(len(v) for v in suites[top].values())
        out.append(f"## {top}")
        out.append("")
        out.append(f"{count} tests.")
        out.append("")
        for group in sorted(suites[top], key=lambda g: (g == "", g)):
            if group:
                out.append(f"### {md_escape(group)}")
                out.append("")
            for name in sorted(suites[top][group]):
                out.append(f"**{md_escape(name)}**")
                out.append("")
                rationale = rationales.get((top, name))
                if rationale:
                    out.append('??? quote "Rationale"')
                    for label, answer in rationale.items():
                        out.append(f"    **{label}** {md_escape(answer)}")
                        out.append("")
                    out.append("")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    documented = sum(1 for top in suites for g in suites[top] for n in suites[top][g] if (top, n) in rationales)
    print(f"wrote {OUTPUT}: {totals['tests']} tests, {documented} with rationale blocks")


if __name__ == "__main__":
    main()
