package eu.inqudium.tabellarium

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class TopicMappingConfigTest {
    @Nested
    inner class `Default topic setter` {
        @Test
        fun `should default to an empty default topic`() {
            // Given / When
            val config = TopicMappingConfig()

            // Then
            assertThat(config.defaultTopic).isEqualTo("")
        }

        @Test
        fun `should trim leading and trailing whitespace when set`() {
            // What is to be tested? Whether the setDefaultTopic setter
            //   (generated by Kotlin from the `var defaultTopic` declaration)
            //   trims its input. Joran passes the raw text content of the
            //   XML element, which typically carries indentation whitespace.
            // How will the test case be deemed successful and why? Successful
            //   if setting "  topic.name  " yields "topic.name" with no
            //   leading or trailing whitespace. This pins down the contract
            //   that the TopicRouter's KAFKA_TOPIC_PATTERN validation
            //   relies on - Kafka topic names with whitespace would be
            //   silently truncated by the broker.
            // Why is it important to test this test case? Without trimming,
            //   a developer who indents the XML for readability would get
            //   "  topic.name  " as the literal topic name, which fails
            //   TopicRouter validation later. Better to trim quietly than
            //   to fail with a confusing error message at startup.

            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "  ichp-de.customerproducts.out  "

            // Then
            assertThat(config.defaultTopic).isEqualTo("ichp-de.customerproducts.out")
        }

        @Test
        fun `should accept subsequent setter calls and use the last value`() {
            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "first.topic"
            config.defaultTopic = "second.topic"

            // Then
            assertThat(config.defaultTopic).isEqualTo("second.topic")
        }
    }

    @Nested
    inner class `Topic router construction` {
        @Test
        fun `should build a TopicRouter routing all events to the configured default`() {
            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val router = config.toTopicRouter()

            // Then: with no markers, the default is returned
            assertThat(router.route(emptyList())).isEqualTo("default.topic")
        }

        @Test
        fun `should propagate TopicRouter validation failure when default topic is blank`() {
            // What is to be tested? Whether configuration errors surface
            //   eagerly at toTopicRouter() rather than being deferred to
            //   later runtime calls - letting the KafkaAppender fail fast
            //   at start() with a clear cause.
            // How will the test case be deemed successful and why? Successful
            //   if calling toTopicRouter() on a config with a blank
            //   defaultTopic throws IllegalArgumentException. This confirms
            //   that the validation pipeline runs end-to-end at startup.
            // Why is it important to test this test case? A silent fallback
            //   to "" as the default topic name would cause every log event
            //   to fail Kafka's topic-name validation at send-time, in the
            //   hot path, after the appender had already reported successful
            //   start - exactly the kind of latent misconfiguration that
            //   the audit's eager-validation principle targets.

            // Given
            val config = TopicMappingConfig() // defaultTopic stays ""

            // When / Then
            assertThatThrownBy { config.toTopicRouter() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("Default topic must not be blank")
        }
    }

    @Nested
    inner class `Topic table construction` {
        @Test
        fun `should build a TopicTable with TECHNICAL as the fallback class`() {
            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.fallbackClass).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable that resolves any topic to the fallback class`() {
            // Given: no explicit topic-to-class mappings configured
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then: every topic - known or unknown - resolves to TECHNICAL
            assertThat(table.classFor("default.topic")).isEqualTo(TopicClass.TECHNICAL)
            assertThat(table.classFor("any.other.topic")).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable whose active classes contain only TECHNICAL`() {
            // What is to be tested? Whether the table's activeTopicClasses
            //   set reflects the minimal configuration: only the fallback
            //   class is active, no others. This drives ProducerRegistry to
            //   instantiate exactly one Kafka producer.
            // How will the test case be deemed successful and why? Successful
            //   if activeTopicClasses contains TECHNICAL and nothing else.
            //   This pins down the single-producer semantics expected for
            //   the minimal legacy configuration.
            // Why is it important to test this test case? If extra classes
            //   leaked into the active set, the ProducerRegistry would
            //   instantiate four KafkaProducers at startup - four times
            //   the network threads and buffer memory, for no benefit, in
            //   a configuration that operationally needs only one.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.activeTopicClasses).containsExactly(TopicClass.TECHNICAL)
        }
    }
}
