package eu.inqudium.tabellarium

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class TopicMappingConfigTest {
    @Nested
    inner class `Default topic setter` {
        @Test
        fun `should default to an empty default topic`() {
            // Given / When
            val config = TopicMappingConfig()

            // Then
            assertThat(config.defaultTopic).isEqualTo("")
        }

        @Test
        fun `should trim leading and trailing whitespace when set`() {
            // What is to be tested? Whether the setDefaultTopic setter
            //   (generated by Kotlin from the `var defaultTopic` declaration)
            //   trims its input. Joran passes the raw text content of the
            //   XML element, which typically carries indentation whitespace.
            // How will the test case be deemed successful and why? Successful
            //   if setting "  topic.name  " yields "topic.name" with no
            //   leading or trailing whitespace. This pins down the contract
            //   that the TopicRouter's KAFKA_TOPIC_PATTERN validation
            //   relies on - Kafka topic names with whitespace would be
            //   silently truncated by the broker.
            // Why is it important to test this test case? Without trimming,
            //   a developer who indents the XML for readability would get
            //   "  topic.name  " as the literal topic name, which fails
            //   TopicRouter validation later. Better to trim quietly than
            //   to fail with a confusing error message at startup.

            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "  ichp-de.customerproducts.out  "

            // Then
            assertThat(config.defaultTopic).isEqualTo("ichp-de.customerproducts.out")
        }

        @Test
        fun `should accept subsequent setter calls and use the last value`() {
            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "first.topic"
            config.defaultTopic = "second.topic"

            // Then
            assertThat(config.defaultTopic).isEqualTo("second.topic")
        }
    }

    @Nested
    inner class `Topic router construction` {
        @Test
        fun `should build a TopicRouter routing all events to the configured default`() {
            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val router = config.toTopicRouter()

            // Then: with no markers, the default is returned
            assertThat(router.route(emptyList())).isEqualTo("default.topic")
        }

        @Test
        fun `should propagate TopicRouter validation failure when default topic is blank`() {
            // What is to be tested? Whether configuration errors surface
            //   eagerly at toTopicRouter() rather than being deferred to
            //   later runtime calls - letting the KafkaAppender fail fast
            //   at start() with a clear cause.
            // How will the test case be deemed successful and why? Successful
            //   if calling toTopicRouter() on a config with a blank
            //   defaultTopic throws IllegalArgumentException. This confirms
            //   that the validation pipeline runs end-to-end at startup.
            // Why is it important to test this test case? A silent fallback
            //   to "" as the default topic name would cause every log event
            //   to fail Kafka's topic-name validation at send-time, in the
            //   hot path, after the appender had already reported successful
            //   start - exactly the kind of latent misconfiguration that
            //   the audit's eager-validation principle targets.

            // Given
            val config = TopicMappingConfig() // defaultTopic stays ""

            // When / Then
            assertThatThrownBy { config.toTopicRouter() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("Default topic must not be blank")
        }
    }

    @Nested
    inner class `Topic table construction` {
        @Test
        fun `should build a TopicTable with TECHNICAL as the fallback class`() {
            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.fallbackClass).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable that resolves any topic to the fallback class`() {
            // Given: no explicit topic-to-class mappings configured
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then: every topic - known or unknown - resolves to TECHNICAL
            assertThat(table.classFor("default.topic")).isEqualTo(TopicClass.TECHNICAL)
            assertThat(table.classFor("any.other.topic")).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable whose active classes contain only TECHNICAL`() {
            // What is to be tested? Whether the table's activeTopicClasses
            //   set reflects the minimal configuration: only the fallback
            //   class is active, no others. This drives ProducerRegistry to
            //   instantiate exactly one Kafka producer.
            // How will the test case be deemed successful and why? Successful
            //   if activeTopicClasses contains TECHNICAL and nothing else.
            //   This pins down the single-producer semantics expected for
            //   the minimal configuration.
            // Why is it important to test this test case? If extra classes
            //   leaked into the active set, the ProducerRegistry would
            //   instantiate four KafkaProducers at startup - four times
            //   the network threads and buffer memory, for no benefit, in
            //   a configuration that operationally needs only one.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.activeTopicClasses).containsExactly(TopicClass.TECHNICAL)
        }
    }

    @Nested
    inner class `Marker mappings` {
        private fun entry(
            marker: String,
            topic: String,
            topicClass: String,
        ): TopicMappingEntry =
            TopicMappingEntry().apply {
                this.marker = marker
                this.topic = topic
                this.topicClass = topicClass
            }

        private fun configWith(vararg entries: TopicMappingEntry): TopicMappingConfig =
            TopicMappingConfig().apply {
                defaultTopic = "default.topic"
                entries.forEach { addMapping(it) }
            }

        @Test
        fun `should route a mapped marker to its topic and classify the topic`() {
            // What is to be tested? The end-to-end effect of a <mapping>
            //   element: the marker routes to the topic, and the topic
            //   carries the configured class - through the same
            //   toTopicRouter/toTopicTable path the appender uses.
            // How will the test case be deemed successful and why? Successful
            //   if the router resolves the marker to the mapped topic and
            //   the table classifies that topic with the mapped class,
            //   while unmapped topics stay on the TECHNICAL fallback.
            // Why is it important to test this test case? This is the
            //   activation path of the entire four-class compliance model;
            //   a silent regression here would strip AUDIT topics of their
            //   mandatory overrides without any startup signal.

            // Given
            val config =
                configWith(
                    entry("SECURITY", "audit.security", "AUDIT"),
                    entry("METRICS", "perf.metrics", "performance"),
                )

            // When
            val router = config.toTopicRouter()
            val table = config.toTopicTable()

            // Then: routing
            val securityMarker = org.slf4j.MarkerFactory.getDetachedMarker("SECURITY")
            assertThat(router.route(listOf(securityMarker))).isEqualTo("audit.security")
            assertThat(router.route(emptyList())).isEqualTo("default.topic")
            // And: classification (topicClass parsing is case-insensitive)
            assertThat(table.classFor("audit.security")).isEqualTo(TopicClass.AUDIT)
            assertThat(table.classFor("perf.metrics")).isEqualTo(TopicClass.PERFORMANCE)
            assertThat(table.classFor("default.topic")).isEqualTo(TopicClass.TECHNICAL)
            assertThat(table.activeTopicClasses)
                .containsExactlyInAnyOrder(TopicClass.AUDIT, TopicClass.PERFORMANCE, TopicClass.TECHNICAL)
        }

        @Test
        fun `should trim whitespace on all entry properties`() {
            // Given: XML-typical indentation whitespace on every value
            val config = configWith(entry("  SECURITY  ", "  audit.security  ", "  AUDIT  "))

            // When / Then
            assertThat(
                config.toTopicRouter().route(
                    listOf(org.slf4j.MarkerFactory.getDetachedMarker("SECURITY")),
                ),
            ).isEqualTo("audit.security")
            assertThat(config.toTopicTable().classFor("audit.security")).isEqualTo(TopicClass.AUDIT)
        }

        @Test
        fun `should reject an unknown topic class with a named error`() {
            // Given
            val config = configWith(entry("SECURITY", "audit.security", "AUDIT_LOGS"))

            // When / Then: the error names the bad value, its mapping, and the valid values
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("AUDIT_LOGS")
                .hasMessageContaining("SECURITY")
                .hasMessageContaining("AUDIT, FUNCTIONAL, TECHNICAL, PERFORMANCE")
        }

        @Test
        fun `should reject the same marker mapped twice`() {
            // What is to be tested? Whether a marker collision fails at
            //   startup instead of silently keeping the last mapping.
            // How will the test case be deemed successful and why? Successful
            //   if toTopicRouter throws and names the duplicated marker.
            //   Map.associate would otherwise silently drop one mapping -
            //   an event stream quietly landing on the wrong topic.
            // Why is it important to test this test case? A silently
            //   dropped AUDIT mapping is a compliance incident, not a
            //   configuration nuance.

            // Given
            val config =
                configWith(
                    entry("SECURITY", "audit.security", "AUDIT"),
                    entry("SECURITY", "other.topic", "TECHNICAL"),
                )

            // When / Then
            assertThatThrownBy { config.toTopicRouter() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("'SECURITY'")
        }

        @Test
        fun `should reject the same topic assigned two different classes`() {
            // Given: two markers routing to one topic with conflicting classes
            val config =
                configWith(
                    entry("SECURITY", "shared.topic", "AUDIT"),
                    entry("MONEY", "shared.topic", "FUNCTIONAL"),
                )

            // When / Then
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("'shared.topic'")
        }

        @Test
        fun `should accept two markers sharing one topic with the same class`() {
            // Given: a legal fan-in - both markers route to one AUDIT topic
            val config =
                configWith(
                    entry("SECURITY", "audit.events", "AUDIT"),
                    entry("MONEY", "audit.events", "AUDIT"),
                )

            // When / Then: no conflict; both markers route there
            val router = config.toTopicRouter()
            assertThat(router.route(listOf(org.slf4j.MarkerFactory.getDetachedMarker("MONEY"))))
                .isEqualTo("audit.events")
            assertThat(config.toTopicTable().classFor("audit.events")).isEqualTo(TopicClass.AUDIT)
        }
    }
}
