package eu.inqudium.tabellarium

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import org.slf4j.MarkerFactory

class TopicMappingConfigTest {
    @Nested
    inner class `Default topic setter` {
        @Test
        fun `should default to an empty default topic`() {
            // What is to be tested? The initial state of a freshly constructed TopicMappingConfig
            //   before Joran has bound any <defaultTopic> element.
            // How will the test case be deemed successful and why? Successful if defaultTopic is
            //   the empty string, not null or a made-up name. This pins the state that
            //   toTopicRouter() later rejects as "must not be blank".
            // Why is it important to test this test case? A non-empty built-in default would let
            //   a configuration that forgot <defaultTopic> start cleanly and route all events to
            //   an unintended topic; the empty default is what turns the omission into a startup
            //   error.

            // Given / When
            val config = TopicMappingConfig()

            // Then
            assertThat(config.defaultTopic).isEqualTo("")
        }

        @Test
        fun `should trim leading and trailing whitespace when set`() {
            // What is to be tested? Whether the setDefaultTopic setter
            //   (generated by Kotlin from the `var defaultTopic` declaration)
            //   trims its input. Joran passes the raw text content of the
            //   XML element, which typically carries indentation whitespace.
            // How will the test case be deemed successful and why? Successful
            //   if setting "  topic.name  " yields "topic.name" with no
            //   leading or trailing whitespace. This pins down the contract
            //   that the TopicRouter's KAFKA_TOPIC_PATTERN validation
            //   relies on - Kafka topic names with whitespace would be
            //   silently truncated by the broker.
            // Why is it important to test this test case? Without trimming,
            //   a developer who indents the XML for readability would get
            //   "  topic.name  " as the literal topic name, which fails
            //   TopicRouter validation later. Better to trim quietly than
            //   to fail with a confusing error message at startup.

            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "  ichp-de.customerproducts.out  "

            // Then
            assertThat(config.defaultTopic).isEqualTo("ichp-de.customerproducts.out")
        }

        @Test
        fun `should accept subsequent setter calls and use the last value`() {
            // What is to be tested? Whether the defaultTopic setter is a plain overwrite - the
            //   last value assigned wins, earlier values are not retained or concatenated.
            // How will the test case be deemed successful and why? Successful if after setting
            //   "first.topic" then "second.topic" the property reads "second.topic". This confirms
            //   the custom trimming setter did not change the property into an append-only one.
            // Why is it important to test this test case? A repeated <defaultTopic> element makes
            //   Joran call the setter twice; last-wins is the behavior Logback users expect from
            //   repeated properties, and a surprising deviation would silently ignore an override.

            // Given
            val config = TopicMappingConfig()

            // When
            config.defaultTopic = "first.topic"
            config.defaultTopic = "second.topic"

            // Then
            assertThat(config.defaultTopic).isEqualTo("second.topic")
        }
    }

    @Nested
    inner class `Topic router construction` {
        @Test
        fun `should build a TopicRouter routing all events to the configured default`() {
            // What is to be tested? The minimal configuration path: a config with only a
            //   <defaultTopic> builds a working TopicRouter.
            // How will the test case be deemed successful and why? Successful if toTopicRouter()
            //   returns a router whose route(emptyList()) yields "default.topic". This confirms
            //   the property value reaches the router's defaultTopic unchanged.
            // Why is it important to test this test case? This is the smallest logback.xml that
            //   should work; if the config-to-router hand-off dropped or altered the name, every
            //   deployment without marker mappings would start but publish to the wrong topic.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val router = config.toTopicRouter()

            // Then: with no markers, the default is returned
            assertThat(router.route(emptyList())).isEqualTo("default.topic")
        }

        @Test
        fun `should propagate TopicRouter validation failure when default topic is blank`() {
            // What is to be tested? Whether configuration errors surface
            //   eagerly at toTopicRouter() rather than being deferred to
            //   later runtime calls - letting the KafkaAppender fail fast
            //   at start() with a clear cause.
            // How will the test case be deemed successful and why? Successful
            //   if calling toTopicRouter() on a config with a blank
            //   defaultTopic throws IllegalArgumentException. This confirms
            //   that the validation pipeline runs end-to-end at startup.
            // Why is it important to test this test case? A silent fallback
            //   to "" as the default topic name would cause every log event
            //   to fail Kafka's topic-name validation at send-time, in the
            //   hot path, after the appender had already reported successful
            //   start - exactly the kind of latent misconfiguration that
            //   the audit's eager-validation principle targets.

            // Given
            val config = TopicMappingConfig() // defaultTopic stays ""

            // When / Then
            assertThatThrownBy { config.toTopicRouter() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("Default topic must not be blank")
        }
    }

    @Nested
    inner class `Topic table construction` {
        @Test
        fun `should build a TopicTable with TECHNICAL as the fallback class`() {
            // What is to be tested? Whether toTopicTable() applies TECHNICAL as the fallback
            //   class when <defaultTopicClass> is not configured.
            // How will the test case be deemed successful and why? Successful if the built
            //   table's fallbackClass is TopicClass.TECHNICAL. This confirms the property's
            //   built-in default survives the case-insensitive resolution into the enum.
            // Why is it important to test this test case? TECHNICAL is the deliberately neutral
            //   class - no compliance mandates, tolerable producer defaults; a different implicit
            //   fallback would impose AUDIT-grade overrides (or weaker ones) on operators who
            //   never asked for them.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.fallbackClass).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable that resolves any topic to the fallback class`() {
            // What is to be tested? Whether a table built without any <mapping> classifies every
            //   topic - the default topic and arbitrary unknown names - via the fallback class.
            // How will the test case be deemed successful and why? Successful if classFor() returns
            //   TECHNICAL for "default.topic" and for "any.other.topic". This confirms the default
            //   topic is not registered as an explicit entry but handled by the fallback.
            // Why is it important to test this test case? The fallback is the safety net that
            //   lets a topic the operator forgot to classify still reach a producer; if lookups
            //   for unmapped names failed instead, a routing typo would crash the log pipeline.

            // Given: no explicit topic-to-class mappings configured
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then: every topic - known or unknown - resolves to TECHNICAL
            assertThat(table.classFor("default.topic")).isEqualTo(TopicClass.TECHNICAL)
            assertThat(table.classFor("any.other.topic")).isEqualTo(TopicClass.TECHNICAL)
        }

        @Test
        fun `should build a TopicTable whose active classes contain only TECHNICAL`() {
            // What is to be tested? Whether the table's activeTopicClasses
            //   set reflects the minimal configuration: only the fallback
            //   class is active, no others. This drives ProducerRegistry to
            //   instantiate exactly one Kafka producer.
            // How will the test case be deemed successful and why? Successful
            //   if activeTopicClasses contains TECHNICAL and nothing else.
            //   This pins down the single-producer semantics expected for
            //   the minimal configuration.
            // Why is it important to test this test case? If extra classes
            //   leaked into the active set, the ProducerRegistry would
            //   instantiate four KafkaProducers at startup - four times
            //   the network threads and buffer memory, for no benefit, in
            //   a configuration that operationally needs only one.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.activeTopicClasses).containsExactly(TopicClass.TECHNICAL)
        }
    }

    @Nested
    inner class `Marker mappings` {
        private fun entry(
            marker: String,
            topic: String,
            topicClass: String,
        ): TopicMappingEntry =
            TopicMappingEntry().apply {
                this.marker = marker
                this.topic = topic
                this.topicClass = topicClass
            }

        private fun configWith(vararg entries: TopicMappingEntry): TopicMappingConfig =
            TopicMappingConfig().apply {
                defaultTopic = "default.topic"
                entries.forEach { addMapping(it) }
            }

        @Test
        fun `should route a mapped marker to its topic and classify the topic`() {
            // What is to be tested? The end-to-end effect of a <mapping>
            //   element: the marker routes to the topic, and the topic
            //   carries the configured class - through the same
            //   toTopicRouter/toTopicTable path the appender uses.
            // How will the test case be deemed successful and why? Successful
            //   if the router resolves the marker to the mapped topic and
            //   the table classifies that topic with the mapped class,
            //   while unmapped topics stay on the TECHNICAL fallback.
            // Why is it important to test this test case? This is the
            //   activation path of the entire four-class compliance model;
            //   a silent regression here would strip AUDIT topics of their
            //   mandatory overrides without any startup signal.

            // Given
            val config =
                configWith(
                    entry("SECURITY", "audit.security", "AUDIT"),
                    entry("METRICS", "perf.metrics", "performance"),
                )

            // When
            val router = config.toTopicRouter()
            val table = config.toTopicTable()

            // Then: routing
            val securityMarker = MarkerFactory.getDetachedMarker("SECURITY")
            assertThat(router.route(listOf(securityMarker))).isEqualTo("audit.security")
            assertThat(router.route(emptyList())).isEqualTo("default.topic")
            // And: classification (topicClass parsing is case-insensitive)
            assertThat(table.classFor("audit.security")).isEqualTo(TopicClass.AUDIT)
            assertThat(table.classFor("perf.metrics")).isEqualTo(TopicClass.PERFORMANCE)
            assertThat(table.classFor("default.topic")).isEqualTo(TopicClass.TECHNICAL)
            assertThat(table.activeTopicClasses)
                .containsExactlyInAnyOrder(TopicClass.AUDIT, TopicClass.PERFORMANCE, TopicClass.TECHNICAL)
        }

        @Test
        fun `should trim whitespace on all entry properties`() {
            // What is to be tested? Whether TopicMappingEntry trims marker, topic and topicClass
            //   on assignment, so XML indentation never becomes part of the configured values.
            // How will the test case be deemed successful and why? Successful if an entry set with
            //   padded values routes the bare SECURITY marker to "audit.security" and classifies
            //   that topic as AUDIT. This confirms trimming on all three setters, end to end.
            // Why is it important to test this test case? Joran passes element text verbatim;
            //   without trimming, "  SECURITY  " would never match a real marker and "  AUDIT  "
            //   would fail class resolution - both showing up as puzzling errors for a
            //   configuration that looks correct.

            // Given: XML-typical indentation whitespace on every value
            val config = configWith(entry("  SECURITY  ", "  audit.security  ", "  AUDIT  "))

            // When / Then
            assertThat(
                config.toTopicRouter().route(
                    listOf(MarkerFactory.getDetachedMarker("SECURITY")),
                ),
            ).isEqualTo("audit.security")
            assertThat(config.toTopicTable().classFor("audit.security")).isEqualTo(TopicClass.AUDIT)
        }

        @Test
        fun `should reject an unknown topic class with a named error`() {
            // What is to be tested? Whether a <topicClass> that is not a TopicClass constant
            //   fails at toTopicTable() with a message that lets the operator find the mistake.
            // How will the test case be deemed successful and why? Successful if the exception
            //   names the bad value ("AUDIT_LOGS"), the mapping's marker ("SECURITY") and the
            //   valid constants. This confirms the error is actionable, not a bare enum failure.
            // Why is it important to test this test case? The class decides producer tuning and
            //   compliance overrides; a typo here must abort start() with a clear pointer
            //   instead of a generic "No enum constant" from deep inside the enum lookup.

            // Given
            val config = configWith(entry("SECURITY", "audit.security", "AUDIT_LOGS"))

            // When / Then: the error names the bad value, its mapping, and the valid values
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("AUDIT_LOGS")
                .hasMessageContaining("SECURITY")
                .hasMessageContaining("AUDIT, FUNCTIONAL, TECHNICAL, PERFORMANCE")
        }

        @Test
        fun `should reject the same marker mapped twice`() {
            // What is to be tested? Whether a marker collision fails at
            //   startup instead of silently keeping the last mapping.
            // How will the test case be deemed successful and why? Successful
            //   if toTopicRouter throws and names the duplicated marker.
            //   Map.associate would otherwise silently drop one mapping -
            //   an event stream quietly landing on the wrong topic.
            // Why is it important to test this test case? A silently
            //   dropped AUDIT mapping is a compliance incident, not a
            //   configuration nuance.

            // Given
            val config =
                configWith(
                    entry("SECURITY", "audit.security", "AUDIT"),
                    entry("SECURITY", "other.topic", "TECHNICAL"),
                )

            // When / Then
            assertThatThrownBy { config.toTopicRouter() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("'SECURITY'")
        }

        @Test
        fun `should reject the same topic assigned two different classes`() {
            // What is to be tested? Whether two <mapping> elements that route to one topic but
            //   declare different classes are rejected at toTopicTable().
            // How will the test case be deemed successful and why? Successful if the exception
            //   is an IllegalArgumentException naming 'shared.topic'. This confirms that the
            //   grouping by topic detects the conflict instead of picking one class arbitrarily.
            // Why is it important to test this test case? A topic has exactly one producer class;
            //   silently choosing AUDIT or FUNCTIONAL would give part of the stream different
            //   delivery guarantees than the operator declared - invisible at runtime.

            // Given: two markers routing to one topic with conflicting classes
            val config =
                configWith(
                    entry("SECURITY", "shared.topic", "AUDIT"),
                    entry("MONEY", "shared.topic", "FUNCTIONAL"),
                )

            // When / Then
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("'shared.topic'")
        }

        @Test
        fun `should classify the default topic via defaultTopicClass`() {
            // What is to be tested? Whether <defaultTopicClass> changes the
            //   class of the default topic (and thereby of every unmapped
            //   topic) without requiring a synthetic marker mapping.
            // How will the test case be deemed successful and why? Successful
            //   if with defaultTopicClass=AUDIT the table classifies the
            //   default topic as AUDIT, the fallback class is AUDIT, and -
            //   with no mappings - AUDIT is the only active class (no
            //   dormant TECHNICAL producer). This pins the direct
            //   configuration path for default-stream compliance grades.
            // Why is it important to test this test case? Before this
            //   element, upgrading the default stream to AUDIT required a
            //   synthetic marker mapping naming the same topic - and left
            //   an unused TECHNICAL producer running.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "audit.trail"
                    defaultTopicClass = "audit"
                }

            // When
            val table = config.toTopicTable()

            // Then
            assertThat(table.fallbackClass).isEqualTo(TopicClass.AUDIT)
            assertThat(table.classFor("audit.trail")).isEqualTo(TopicClass.AUDIT)
            assertThat(table.activeTopicClasses).containsExactly(TopicClass.AUDIT)
        }

        @Test
        fun `should reject an unknown defaultTopicClass with a named error`() {
            // What is to be tested? Whether an invalid <defaultTopicClass> value fails at
            //   toTopicTable() with an error that points at the element.
            // How will the test case be deemed successful and why? Successful if the exception
            //   mentions "<defaultTopicClass>", the bad value "IMPORTANT" and the list of valid
            //   constants. This confirms the fallback class goes through the same named
            //   validation as per-mapping classes.
            // Why is it important to test this test case? The fallback class governs every
            //   unmapped topic; an unrecognized value must not quietly degrade to TECHNICAL when
            //   the operator meant AUDIT, and the error must say which element to fix.

            // Given
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "default.topic"
                    defaultTopicClass = "IMPORTANT"
                }

            // When / Then
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("<defaultTopicClass>")
                .hasMessageContaining("IMPORTANT")
                .hasMessageContaining("AUDIT, FUNCTIONAL, TECHNICAL, PERFORMANCE")
        }

        @Test
        fun `should reject a mapping that assigns the default topic a conflicting class`() {
            // What is to be tested? Whether a <mapping> naming the default
            //   topic with a class contradicting <defaultTopicClass> fails
            //   at startup.
            // How will the test case be deemed successful and why? Successful
            //   if toTopicTable throws and names both classes. Marker-less
            //   events and mapped events landing on the same topic must
            //   never diverge in delivery guarantees.
            // Why is it important to test this test case? Silently letting
            //   one side win would give part of the default stream weaker
            //   (or different) guarantees than the operator declared -
            //   a compliance discrepancy invisible at runtime.

            // Given: default topic TECHNICAL (implicit), mapping says AUDIT
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "shared.topic"
                    addMapping(
                        TopicMappingEntry().apply {
                            marker = "SECURITY"
                            topic = "shared.topic"
                            topicClass = "AUDIT"
                        },
                    )
                }

            // When / Then
            assertThatThrownBy { config.toTopicTable() }
                .isInstanceOf(IllegalArgumentException::class.java)
                .hasMessageContaining("'shared.topic'")
                .hasMessageContaining("TECHNICAL")
                .hasMessageContaining("AUDIT")
        }

        @Test
        fun `should accept a mapping that names the default topic with the same class`() {
            // What is to be tested? The positive counterpart of the conflict check: a <mapping>
            //   may route a marker to the default topic when its class agrees with
            //   <defaultTopicClass>.
            // How will the test case be deemed successful and why? Successful if toTopicTable()
            //   builds without throwing and classifies "audit.trail" as AUDIT. This confirms the
            //   agreement check compares classes, not merely the presence of the topic.
            // Why is it important to test this test case? Routing an explicit marker to the
            //   default stream is a legitimate setup; rejecting it would force operators into
            //   a duplicate topic just to satisfy validation.

            // Given: defaultTopicClass and the mapping agree on AUDIT
            val config =
                TopicMappingConfig().apply {
                    defaultTopic = "audit.trail"
                    defaultTopicClass = "AUDIT"
                    addMapping(
                        TopicMappingEntry().apply {
                            marker = "SECURITY"
                            topic = "audit.trail"
                            topicClass = "AUDIT"
                        },
                    )
                }

            // When / Then: consistent - accepted
            val table = config.toTopicTable()
            assertThat(table.classFor("audit.trail")).isEqualTo(TopicClass.AUDIT)
        }

        @Test
        fun `should accept two markers sharing one topic with the same class`() {
            // What is to be tested? Whether fan-in - several markers routing to one topic with
            //   an identical class - passes the same-topic conflict check.
            // How will the test case be deemed successful and why? Successful if router and table
            //   build without error, MONEY routes to "audit.events" and the topic is AUDIT. This
            //   confirms the conflict check compares the set of classes, not the number of mappings.
            // Why is it important to test this test case? Collecting several audit-relevant
            //   markers into one AUDIT topic is the expected way to use the mapping; an
            //   over-strict check would reject the most common compliance layout.

            // Given: a legal fan-in - both markers route to one AUDIT topic
            val config =
                configWith(
                    entry("SECURITY", "audit.events", "AUDIT"),
                    entry("MONEY", "audit.events", "AUDIT"),
                )

            // When / Then: no conflict; both markers route there
            val router = config.toTopicRouter()
            assertThat(router.route(listOf(MarkerFactory.getDetachedMarker("MONEY"))))
                .isEqualTo("audit.events")
            assertThat(config.toTopicTable().classFor("audit.events")).isEqualTo(TopicClass.AUDIT)
        }
    }
}
